### PR TITLE
Add an empty package list

### PR DESCRIPTION
**Pull request by RajeshKumarSrivastava**
Adds en empty package_list.txt file. This file will serve as a package list for the automotive offering

### CODE REVIEW

**Comment by RajeshKumarSrivastava** [comment]
@lioramilbaum @HubertStefanski @JaneSoo  I am not sure why the PR attributes like adding a reviewer is not enabled here. Please review it. Please suggest on names and folder structure

**Comment by JaneSoo** [comment]
@RajeshKumarSrivastava not sure if .txt will be convenient?

**Comment by lmilbaum** [comment]
> @RajeshKumarSrivastava not sure if .txt will be convenient?

You are probably right. Let's reveal it as we move forward. For now it is more then enough.

**Review by hubeadmin — APPROVED** [review]
LGTM :+1:  `.txt` should be sufficient, don't think we have any requirement to format this as long as we adhere to new lines on our end

**Review by lmilbaum — APPROVED** [review]
LGTM

**Review by JaneSoo — APPROVED** [review]

**Pull request merged**
