### PR TITLE
hotfix: Use bareurl instead of mirrorlist at the centos sources

### PR DESCRIPTION
**Pull request by juanje**
The selected mirror by yum/dnf/osbuild was failing trying to fetch the package `lvm-compat-libs` (something wrong at the mirror), which was causing the `osbuild` to run indefinitely and trigger the GitHub Actions' timeout.

This is external error (the 'http://d36uatko69830t.cloudfront.net' CentOS mirror), but it was making all the pipelines to fail due the timeout, so it needed to be fixed in order to have the pipeline running again.

### CODE REVIEW

**Comment by juanje** [comment]
It seems that the creation of the commit was failing due an error with the CentOS Stream 8 yum-mirrors:
```
Jul 03 00:40:40 [server] systemd[1]: osbuild-worker@1.service: Main process exited, code=exited, status=1/FAILURE
Jul 03 00:40:40 [server] systemd[1]: osbuild-worker@1.service: Failed with result 'exit-code'.
Jul 03 00:40:41 [server] systemd[1]: osbuild-worker@1.service: Service RestartSec=1s expired, scheduling restart.
Jul 03 00:40:41 [server] systemd[1]: osbuild-worker@1.service: Scheduled restart job, restart counter is at 636.
Jul 03 00:40:41 [server] systemd[1]: Stopped OSBuild Composer Worker (1).
Jul 03 00:40:41 [server] systemd[1]: Started OSBuild Composer Worker (1).
Jul 03 00:40:41 [server] osbuild-worker[1917412]: Waiting for a new job...
Jul 03 00:40:52 [server] osbuild-worker[1917412]: Running 'osbuild' job 13cd6cbb-306c-4966-8039-041953316a35
Jul 03 00:40:54 [server] osbuild-worker[1917412]: Traceback (most recent call last): 
Jul 03 00:40:54 [server] osbuild-worker[1917412]:   File "/usr/bin/osbuild", line 11, in <module>
Jul 03 00:40:54 [server] osbuild-worker[1917412]:     load_entry_point('osbuild==27.2', 'console_scripts', 'osbuild')()
Jul 03 00:40:54 [server] osbuild-worker[1917412]:   File "/usr/lib/python3.6/site-packages/osbuild/main_cli.py", line 141, in osbuild_cli
Jul 03 00:40:54 [server] osbuild-worker[1917412]:     output_directory=output_directory  
Jul 03 00:40:54 [server] osbuild-worker[1917412]:   File "/usr/lib/python3.6/site-packages/osbuild/pipeline.py", line 282, in build
Jul 03 00:40:54 [server] osbuild-worker[1917412]:     source.download(store, libdir)     
Jul 03 00:40:54 [server] osbuild-worker[1917412]:   File "/usr/lib/python3.6/site-packages/osbuild/sources.py", line 55, in download
Jul 03 00:40:54 [server] osbuild-worker[1917412]:     raise RuntimeError(f"{source}: " + reply["error"])
Jul 03 00:40:54 [server] osbuild-worker[1917412]: RuntimeError: org.osbuild.curl: curl: error downloading {'url': 'http://d36uatko69830t.cloudfront.net/centos/8-stream/AppStream/aarch64/os/Packages/llvm-compat-libs-11.0.1-1.module_el8.5.0+840+21214faf.aarch64.rpm'}: error code 22
Jul 03 00:40:54 [server] osbuild-worker[1917412]: 2021/07/03 00:40:54 Job 13cd6cbb-306c-4966-8039-041953316a35 failed: error decoding osbuild output: unexpected end of JSON input
Jul 03 00:40:54 [server] osbuild-worker[1917412]: the raw output:
Jul 03 00:40:54 [server] osbuild-worker[1917412]: Waiting for a new job...
```

**Comment by juanje** [comment]
I'll merge this hotfix to avoid have other people blocked by this.

**Comment by lmilbaum** [comment]
@juanje Please help me understand this fix?

**Comment by juanje** [comment]
@lioramilbaum The **Image Builder** (`osbuild`) is installed in the bare-metal machine where we run all these steps via `tmt`:
1. Build the "OSTree commit". (`create-commit.sh`)
1. Install the commit into a virtual machine (VM). (`install-vm.sh`)
1. Start the VM for running the smoke tests. (`test-vm.sh`)

The `osbuild` is using the **CentOS Stream 8** sources to build the `commit` (the first step), but the repository file is using `mirrorlist`, which tells yum/dnf to look up for the closest mirror for download the packages.
This options is usually the best, but now it was giving us troubles because the closest mirror was broken and `osbuild` was failing trying to download a package that wasn't in the mirror. Look at the description of this PR for more details on that.

As `osbuild` need to download all the packages indicated at the `blueprint` and its dependencies to be able to create the "ostree commit", it was stuck at that point and it hit the GitHub Actions timeout, which cut the connection with the bare-metal machine, so the process was still running at the machine, but it couldn't finish.
And as the mirror was still broken, every new PR will hit the same issue, failing not because the PR itself, but because of the mirror.

So, the temporary solution was to set at the sources the field `baseurl`, instead of `mirrorlist`, so we could point to a mirror that was actually working:
https://github.com/osbuild/automotive-ci/blob/main/tests/ci/files/centos-stream-8.json#L5

The next PR #61 was supposed to be part of this one, but I forgot to add those changes to the commit :(

At first I thought I was just taking more time than usual (due network issues), so changing the timeout seemed as a good idea at the time. That's why the initial PR was about the `timeout`, but after debugging at the bare-metal machine, I found out about the mirror issue and I came out with this fix.

**Pull request merged**
