### PR TITLE
retained el8 in the release name, earlier it was stripped 

### PR DESCRIPTION
**Pull request by RajeshKumarSrivastava**
Added "el8" in the release name missed earlier and removed spaces in beginning of the nvr

### CODE REVIEW

**Review by hubeadmin — APPROVED** [review]
lgtm! 

Just on a personal curiosity note, I assume that el8 stands for `Enterprise Linux 8`, but what's the purpose of it in the package nvr?

**Review by JaneSoo — APPROVED** [review]
lgtm

**Comment by RajeshKumarSrivastava** [comment]
> lgtm!
> 
> Just on a personal curiosity note, I assume that el8 stands for `Enterprise Linux 8`, but what's the purpose of it in the package nvr?

el8 is part of the release and therefore you can have updates like *el8_1, *el8_2

**Comment by RajeshKumarSrivastava** [comment]
I believe we are good to merge

**Pull request merged**
