### PR TITLE
Remove the ssh key and generate a temporary each time

### PR DESCRIPTION
**Pull request by juanje**
Although, the ssh keys stored at the repository are just used with the temporary VM that is generated when runs the CI, it's a good practice not to store ssh keys in public repositories.

Changes:
* Remove the current ssh key file and the private key from inside the kickstart template.
* Generate a ssh keys pairs during the CI run:
  * The public key is stored in a file (which lives just during the CI run).
  * The private key is embedded into the generated kickstart file.

### CODE REVIEW

**Review by lmilbaum — APPROVED** [review]

**Review by thrix — APPROVED** [review]
LGTM

**Comment by thrix** [comment]
@juanje just the tests are not happy, looking at the problem, I wonder what went wrong ...

**Comment by juanje** [comment]
> @juanje just the tests are not happy, looking at the problem, I wonder what went wrong ...


Yeah, @thrix , I'm looking right now at the issue and I'm not sure. I reproduced the key generation and try to use the keys on other machine and it worked. No permission errors...
But I discover a forgotten call to a old function (`clean_up`). I removed it.

I'll push a verbose option to the SSH, so we can see better the error.

**Comment by juanje** [comment]
@thrix I found the error... I put the variable `$SSH_PUBLIC_KEY` (which contain the PATH for the private key) in the kickstart file, instead of putting the content of the file :facepalm: 

I change it so I put the content of the file in another variable and that is the one that goes in the kickstart file.

**Pull request merged**
