### PR TITLE
Add package list from centos stream

### PR DESCRIPTION
**Pull request by RajeshKumarSrivastava**
Add packages for the automotive base image based on centos stream 8

### CODE REVIEW

**Comment by RajeshKumarSrivastava** [comment]
This list is something that I created sub automatic. I took the complete rpm list of centos stream from here https://www.centos.org/centos-stream/ and extracted the equivalent packages matching from the package list from RHEL 8.4 package list from the image here http://file.rdu.redhat.com/~rasibley/imagebuilder/8.4/ . I will reconcile it further because I see there are packages with same version and different releases are also part of this. I am not sure if there should/can be packages with same version and different releases

**Review by JaneSoo — APPROVED** [review]
The same package with different releases will need discussion around how the diff should handle otherwise LGTM.

**Review by hubeadmin — APPROVED** [review]
/lgtm

/approve

The issue with the same packages having different versions has me a bit worried, there's a bit of thinking that we'll have to do to get around this.
To get around this we would probably have to get some more in-depth diff checks going, I don't think a simple difference will cut it for us, we might have to implement a `updateFrom` and `UpdateTo` check to ensure that we're updating the correct package and version (and also ensure that we're only updating one package at a time where the same, differently versioned package exists)

^^ isn't a blocker to having this merged though, so I'm happy with this list.

**Comment by lmilbaum** [comment]
Please update the PR description. It still states that those are RHEL packages. We don't want to confuse contributors.

**Comment by RajeshKumarSrivastava** [comment]
> /lgtm
> 
> /approve
> 
> The issue with the same packages having different versions has me a bit worried, there's a bit of thinking that we'll have to do to get around this.
> To get around this we would probably have to get some more in-depth diff checks going, I don't think a simple difference will cut it for us, we might have to implement a `updateFrom` and `UpdateTo` check to ensure that we're updating the correct package and version (and also ensure that we're only updating one package at a time where the same, differently versioned package exists)
> 
> ^^ isn't a blocker to having this merged though, so I'm happy with this list.

May be don't need to, the ultimate list should come from an centos base image and that list should not have this problem 

> Please update the PR description. It still states that those are RHEL packages. We don't want to confuse contributors.

done

**Comment by RajeshKumarSrivastava** [comment]
> /lgtm
> 
> /approve
> 
> The issue with the same packages having different versions has me a bit worried, there's a bit of thinking that we'll have to do to get around this.
> To get around this we would probably have to get some more in-depth diff checks going, I don't think a simple difference will cut it for us, we might have to implement a `updateFrom` and `UpdateTo` check to ensure that we're updating the correct package and version (and also ensure that we're only updating one package at a time where the same, differently versioned package exists)
> 
> ^^ isn't a blocker to having this merged though, so I'm happy with this list.

**Comment by thrix** [comment]
@RajeshKumarSrivastava wouldn't be better to call the file something like:

`package_list/centos-stream-8.txt`

In case we would have more package lists (maybe for CentOS Stream 9? or anything else?)

**Comment by hubeadmin** [comment]
>@RajeshKumarSrivastava wouldn't be better to call the file something like:
> package_list/centos-stream-8.txt
> In case we would have more package lists (maybe for CentOS Stream 9? or anything else?)

I like that idea, It might require a small refactor in Dover, but it's nothing overly complicated. @RajeshKumarSrivastava let me know if you decide to go ahead with the renaming :+1:

**Comment by RajeshKumarSrivastava** [comment]
> @RajeshKumarSrivastava wouldn't be better to call the file something like:
> 
> `package_list/centos-stream-8.txt`
> 
> In case we would have more package lists (maybe for CentOS Stream 9? or anything else?)

Thanks. It make more sense now to do a concrete naming, since we decided we should support multiple pipeline for the versions. For now I am not sure though what should be the concrete name for this file honestly. AFAIU centos stream 8 is a down stream of rhel8 while centos stream 9 is the upstream for rhel 9. For 8 we might listen to rhel8 package changes since those will be upstream changes for the base RHEL-8 packages. May be we name it as "rhel8.4-automotive-base.txt"

**Review by lmilbaum — APPROVED** [review]

**Pull request merged**
